apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-optimizer
  template:
    metadata:
      labels:
        app: image-optimizer
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: optimizer
        image: pillaisathya/image-optimizer:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: image-optimizer-secret
              key: API_KEY
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
