apiVersion: v1
kind: Service
metadata:
  name: image-optimizer-service
spec:
  selector:
    app: image-optimizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
